src/plastics_eol/urls.py
# urls.py (plastics_eol)
# !/usr/bin/env python3
# coding=utf-8

from django.contrib import admin
from django.urls import path, include
from .views import home, contact, about, ConditionsCreate, ConditionsDetail, \
    MSWCompositionCreate, MSWCompostCreate, MSWIncinerationCreate, \
    MSWLandfillCreate, MSWRecyclingCreate, \
    PlasticRecyclingCreate, PlasticIncinerationCreate, PlasticLandfillCreate, \
    PlasticReportedCreate, PlasticImportCreate, PlasticExportCreate, \
    PlasticReExportCreate, ScenarioCreate, ScenarioDetail, ScenarioList, \
    run_calculations, ScenarioResults, ScenarioReview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('disclaimers/', include('disclaimers.urls', namespace='disclaimers')),
    path('support/', include('support.urls', namespace='support')),
    path('teams/', include('teams.urls', namespace='teams')),

    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),

    path('scenario/', ScenarioList.as_view(), name='scenario'),
    path('scenario/create/', ScenarioCreate.as_view(), name='scenario_create'),
    path('scenario/<int:pk>/',
         ScenarioDetail.as_view(),
         name='scenario_detail'),

    path('scenario/<int:pk>/run/', run_calculations, name='run_calculations'),

    path('scenario/<int:pk>/review/',
         ScenarioReview.as_view(),
         name='scenario_review'),

    path('scenario/<int:pk>/results/',
         ScenarioResults.as_view(),
         name='scenario_results'),

    path('scenario/<int:pk>/conditions/',
         ConditionsDetail.as_view(),
         name='conditions_detail'),
    path('scenario/<int:pk>/conditions/create',
         ConditionsCreate.as_view(),
         name='conditions_create'),

    # path('scenario/<int:pk>/msw_composition/',
    #    MSWCompositionDetail.as_view(),
    #    name='msw_composition_detail'),
    path('scenario/<int:pk>/msw_composition/create',
         MSWCompositionCreate.as_view(),
         name='msw_composition_create'),

    # path('scenario/<int:pk>/msw_recycling/',
    #      MSWRecyclingDetail.as_view(),
    #      name='msw_recycling_detail'),
    path('scenario/<int:pk>/msw_recycling/create',
         MSWRecyclingCreate.as_view(),
         name='msw_recycling_create'),

    # path('scenario/<int:pk>/msw_incineration/',
    #      MSWIncinerationDetail.as_view(),
    #      name='msw_incineration_detail'),
    path('scenario/<int:pk>/msw_incineration/create',
         MSWIncinerationCreate.as_view(),
         name='msw_incineration_create'),

    # path('scenario/<int:pk>/msw_landfill/',
    #      MSWLandfillDetail.as_view(),
    #      name='msw_landfill_detail'),
    path('scenario/<int:pk>/msw_landfill/create',
         MSWLandfillCreate.as_view(),
         name='msw_landfill_create'),

    # path('scenario/<int:pk>/msw_compost/',
    #      MSWCompostDetail.as_view(),
    #      name='msw_compost_detail'),
    path('scenario/<int:pk>/msw_compost/create',
         MSWCompostCreate.as_view(),
         name='msw_compost_create'),

    # ################################################################

    path('scenario/<int:pk>/plastic_recycling_create/create',
         PlasticRecyclingCreate.as_view(),
         name='plastic_recycling_create'),

    path('scenario/<int:pk>/plastic_incineration_create/create',
         PlasticIncinerationCreate.as_view(),
         name='plastic_incineration_create'),

    path('scenario/<int:pk>/plastic_landfill_create/create',
         PlasticLandfillCreate.as_view(),
         name='plastic_landfill_create'),

    path('scenario/<int:pk>/plastic_reported_create/create',
         PlasticReportedCreate.as_view(),
         name='plastic_reported_create'),

    path('scenario/<int:pk>/plastic_imported_create/create',
         PlasticImportCreate.as_view(),
         name='plastic_imported_create'),

    path('scenario/<int:pk>/plastic_exported_create/create',
         PlasticExportCreate.as_view(),
         name='plastic_exported_create'),

    path('scenario/<int:pk>/plastic_reexported_create/create',
         PlasticReExportCreate.as_view(),
         name='plastic_reexported_create'),
]

src/support/urls.py
# urls.py (support)
# !/usr/bin/env python3
# coding=utf-8
# pylint: skip-file
# We disable the invalid name because urlpatterns is the Django default

"""URLs and routing for the Support module."""

from django.urls import re_path
from .views import index, UserManualView, download_manual, EventsView, \
    ReferencesView, event_file_download, SuggestionCreateView, \
    SuggestionEditView, delete_support, list_supports, show_support, \
    file_upload_support, delete_support_attachment, create_support_type, \
    edit_support_type, delete_support_type, list_support_types, \
    show_support_type, create_priority, edit_priority, delete_priority, \
    list_priorities, show_priority

app_name = 'support'

urlpatterns = [
    re_path(r'^$', index),
    re_path(r'^index/$', index, name='go_to_support'),

    re_path(
        r'^documentation/$', UserManualView.as_view(), name="documentation"),
    re_path(r'^download_manual/$', download_manual, name="download_manual"),
    re_path(r'events/', EventsView.as_view(), name='events'),
    re_path(r'references/', ReferencesView.as_view(), name='references'),

    re_path(
        r'^files/(?P<file_name>.+)/$', event_file_download,
        name='event_file_download'),

    re_path(r'^create/(?P<support_type_name>\w+)/$',
            SuggestionCreateView.as_view(), name='create_support'),
    re_path(r'^edit/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$',
            SuggestionEditView.as_view(), name='edit_support'),
    re_path(r'^delete/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$',
            delete_support, name='delete_support'),
    re_path(r'^list/(?P<support_type_name>\w+)/$',
            list_supports, name='list_supports'),
    re_path(r'^show/(?P<obj_id>\d+)/$', show_support, name='show_support'),

    # new
    re_path(r'^file/upload/(?P<obj_id>\d+)/$',
            file_upload_support, name='file_upload_support'),
    re_path(r'^support_attachment/delete/(?P<obj_id>\d+)/$',
            delete_support_attachment, name='delete_support_attachment'),

    re_path(r'^type/create/$',
            create_support_type, name='create_support_type'),
    re_path(r'^type/edit/(?P<obj_id>\d+)/$',
            edit_support_type, name='edit_support_type'),
    re_path(r'^type/delete/(?P<obj_id>\d+)/$',
            delete_support_type, name='delete_support_type'),
    re_path(r'^type/list/$', list_support_types, name='list_support_types'),
    re_path(r'^type/show/(?P<obj_id>\d+)/$',
            show_support_type, name='show_support_type'),

    re_path(r'^priority/create/$',
            create_priority, name='create_priority'),
    re_path(r'^priority/edit/(?P<obj_id>\d+)/$',
            edit_priority, name='edit_priority'),
    re_path(r'^priority/delete/(?P<obj_id>\d+)/$',
            delete_priority, name='delete_priority'),
    re_path(r'^priority/list/$',
            list_priorities, name='list_priorities'),
    re_path(r'^priority/show/(?P<obj_id>\d+)/$',
            show_priority, name='show_priority'),
]

src/teams/urls.py
# urls.py (teams)
# !/usr/bin/env python3
# coding=utf-8
# py-lint: disable=invalid-name
# We disable the invalid name because urlpatterns is the Django default

"""
URLs related to managing teams of users.

Available functions:
- REST api for teams
- Team management
"""

from django.urls import re_path
from teams.views import APITeamListView, APITeamDetailView, \
    APITeamMembershipListView, APITeamMembershipDetailView, \
    TeamCreateView, TeamManagementView, TeamEditView, TeamListView

app_name = 'teams'

urlpatterns = [

    # REST api for teams.
    re_path(r'^api/team/$', APITeamListView.as_view(), name='api_team_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/$', APITeamDetailView.as_view(),
            name='api_team_detail'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/$',
            APITeamMembershipListView.as_view(),
            name='api_team_membership_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/(?P<membership_id>\d+)/$',
            APITeamMembershipDetailView.as_view(),
            name='api_team_membership_detail'),

    # Team management.
    re_path(r'^team/$', TeamCreateView.as_view(), name='team_create'),
    re_path(r'^list/$', TeamListView.as_view(), name='team_list'),
    re_path(r'^team/(?P<team_id>\d+)/manage$', TeamManagementView.as_view(),
            name='team_manage'),
    re_path(r'^team/(?P<team_id>\d+)/edit$', TeamEditView.as_view(),
            name='team_edit'),
]

src/support/forms.py
# py (support)
# !/usr/bin/env python3
# coding=utf-8
# pylint: skip-file
"""
Form used to manage support issues.

Available functions:
"""

from django.forms import ModelForm, CharField, TextInput, Textarea, DateField
from django.utils.translation import gettext_lazy as _
from support.models import Support, Priority, SupportType


class SupportForm(ModelForm):
    """A Form For Creating a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Support form to send to Django Admin."""
        super(SupportForm, self).__init__(*args, **kwargs)

    required_css_class = 'required'

    id = CharField(label=_("Reference Num"),
                   widget=TextInput(attrs={
                       'class': 'usa-input',
                       'readonly': 'readonly'
                   }),
                   required=False)
    subject = CharField(label=_("Subject"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)

    the_description = CharField(label=_("Description"),
                                widget=Textarea(attrs={'class': 'usa-input'}),
                                required=True)
    weblink = CharField(label=_("Email Address"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)

    class Meta:
        """Support link."""

        model = Support
        fields = (
            "id",
            "subject",
            "the_description",
            "weblink",
        )


class SupportAdminForm(ModelForm):
    """A Form For Responding To a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Support Django Admin form."""
        super(SupportAdminForm, self).__init__(*args, **kwargs)

    required_css_class = 'required'

    id = CharField(label=_("Reference Num"),
                   widget=TextInput(attrs={
                       'class': 'usa-input',
                       'readonly': 'readonly'
                   }),
                   required=False)
    subject = CharField(label=_("Subject"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)
    date_resolved = DateField(
        label=_("Date Resolved"),
        widget=TextInput(attrs={'class': 'usa-input date-control'}),
        required=False)
    the_description = CharField(label=_("Description"),
                                widget=Textarea(attrs={'class': 'usa-input'}),
                                required=True)
    weblink = CharField(label=_("Email Address"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)
    review_notes = CharField(label=_("Review Notes"),
                             widget=Textarea(attrs={'class': 'usa-input'}),
                             help_text="Notes from review of suggestion",
                             required=False)

    class Meta:
        """All fields to complete support form."""

        model = Support
        fields = (
            "id",
            "subject",
            "the_description",
            "weblink",
            "date_resolved",
            "review_notes",
        )


class SupportTypeForm(ModelForm):
    """A Form For Creating a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Form type."""
        super(SupportTypeForm, self).__init__(*args, **kwargs)

    required_css_class = 'required'
    the_name = CharField(label=_("Support Type"),
                         widget=TextInput(attrs={'class': 'usa-input'}),
                         required=False)

    class Meta:
        """Name form."""

        model = SupportType
        fields = ("the_name", )


class PriorityForm(ModelForm):
    """A Form For Creating a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Form priority."""
        super(PriorityForm, self).__init__(*args, **kwargs)

    the_name = CharField(label=_("Priority"),
                         widget=TextInput(attrs={'class': 'usa-input'}),
                         required=False)

    class Meta:
        """Form priority.."""

        model = Priority
        fields = ("the_name", )

src/support/templates/main/create_help_request.html
{% extends 'base/site_base_support.html' %}
{% block support_content %}

<h3>Enter request, save, add any attachments, submit</h3>
<form class="form-horizontal" enctype="multipart/form-data" method="post" action="." role="form" novalidate>
    {% csrf_token %}
    {% if form.errors %}
    <div class="usa-alert usa-alert--error" role="alert">
        <div class="usa-alert__body">
            <h5 class="usa-alert__heading">Please correct the following errors</h5>
            {% for field in form %}
            {% if field.errors %}
            <p class="usa-alert__text">{{field.label_tag}} {{ field.errors|striptags }}</p>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% if success %}
    <div class="usa-alert usa-alert--success">
        <div class="usa-alert__body">
            <p class="usa-alert__text">The help request has been created.</p>
        </div>
    </div>
    {% endif %}

    {% for field in form %}
    <div class="usa-form-group">
        <label class="usa-label">
            <div>{{field.label_tag}}</div>
            <div class="definition">{{field.help_text}}</div>
        </label>
        {{field}}
        {% if field.errors %}
        <div class="usa-alert usa-alert--error" role="alert">
            <div class="usa-alert__body">
                <p class="usa-alert__text">{{field.errors.as_text}}</p>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    <div class="usa-form-group">
        <input type="submit" value="Save" class="usa-button">
    </div>
</form>
{% endblock %}

src/support/templates/main/create_support.html
{% extends 'base/site_base_support.html' %}
{% block support_content %}

<h3>{{title}}</h3>
<p>{{instructions}}</p>

<form class="form-horizontal " enctype="multipart/form-data" method="post" action="." role="form" novalidate>
    {% csrf_token %}
    {% if form.errors %}
    <div class="usa-alert usa-alert--error" role="alert">
        <div class="usa-alert__body">
            <h5 class="usa-alert__heading">Please correct the following errors</h5>
            {% for field in form %}
            {% if field.errors %}
            <p class="usa-alert__text">{{field.label_tag}} {{ field.errors|striptags }}</p>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% for field in form %}
    <div class="usa-form-group">
        <label class="usa-label">
            <div>{{field.label_tag}}</div>
            <div class="definition">{{field.help_text}}</div>
        </label>
        {{field}}
        {% if field.errors %}
        <div class="usa-alert usa-alert--error" role="alert">
            <div class="usa-alert__body">
                <p class="usa-alert__text"> {{field.errors.as_text}}</p>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    <div class="usa-form-group">
        <input type="submit" value="Save" class="usa-button">
    </div>
</form>
{% endblock %}

src/support/templates/main/email.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>
    </head>
    <body>
        <p>{{ user_name }}</p>
        <p>{{ subject }}</p>
    </body>
</html>

src/support/templates/main/events.html
{% extends 'main/base.html' %}
{% block content %}
<h2>Upcoming Events</h2>
<h4>
    Check back often for upcoming events, presentations,
    training sessions, and more on the {{APP_NAME}} tool.
</h4>
<hr />
<ul class="usa-card-group">
    <li class="usa-card usa-card--flag tablet:grid-col-12">
        <div class="usa-card__container">
            <header class="usa-card__header">
                <h4 class="usa-card__heading">
                    Example
                </h4>
            </header>
            <div class="usa-card__media grid-col-3">
                <div class="usa-card__img">
                    <div class="margin-2em">
                        <h4>TUE</h4>
                        <h4>November 1</h4>
                        <h4>2022</h4>
                    </div>
                </div>
            </div>
            <div class="usa-card__body">
                <!-- NOTE: This section is paragraph text in an event card's body. -->
                <p>
                    Created this page. <mark>Use as an example.</mark>
                </p>
            </div>
        </div>
    </li>
</ul>
{% endblock %}

src/support/templates/main/manual.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="white-box">
    <h3>{{APP_NAME}} Introduction</h3>
    <div>
        <p>{{APP_DESCRIPTION_SHORT}}</p>
    </div>
    <div>
        <div class="well">
            <h4>Quick links</h4>
            {#<div><a href="{% url 'citation' %}">Download Citations (txt)</a></div>#}
            <div><a href="{% url 'support:download_manual' %}">View the {{APP_NAME}} user manual</a></div>
            <div><a href="{% url 'home' %}">Access the Home page</a></div>
        </div>
    </div>
</div>

{% endblock %}

src/support/templates/main/no_edit.html
{% extends 'base/site_base_support.html' %}
{% load humanize %}

{% block support_content %}

<h3>{{APP_NAME}} Help/Suggestions</h3>
<p>
    You are not currently authorized to edit suggestions submitted by others.
</p>
{% endblock %}

src/support/templates/main/references.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="white-box">
    <h3>References used for this project study.</h3>
    <p>
        Below is a list of the articles, manuals, and research papers used
        for this project and are listed strictly for reference purposes.
    </p>

    <h4>Disclaimer of Endorsement.</h4>
    <p>
        Mention of or referral to commercial products or services, and/or
        links to non-EPA sites does not imply official EPA endorsement of or
        responsibility for the opinions, ideas, data, or products presented at
        those locations, or guarantee the validity of the information provided.
        Mention of commercial products/services on non-EPA websites is provided
        soley as a pointer to information on topics related to environmental
        protection that may be useful to EPA staff and the public.
    </p>

    <h4>Notice.</h4>
    <p>
        Information from the EPA website resides on numerous computer systems
        funded by the Agency. The use of the EPA websites may be monitored for
        computer security purposes. Any unauthorized access to the EPA website
        is prohibited and is subject to criminal and civil penalties under federal
        laws including, but not limited to, Public Law 99-474, the Computer Fraud
        and Abuse Act of 1986.
    </p>
</div>

{% endblock %}

src/support/templates/main/support.html
{% extends 'base/site_base_support.html' %}
{% load humanize %}

{% block support_content %}

<h3>{{APP_NAME}} Help/Suggestions</h3>
<p>
    Select an option to request help or make a suggestion.
</p>
{% endblock %}