src/plastics_eol/urls.py
# urls.py (plastics_eol)
# !/usr/bin/env python3
# coding=utf-8

from django.contrib import admin
from django.urls import path, include
from .views import home, contact, about, ConditionsCreate, ConditionsDetail, \
    MSWCompositionCreate, MSWCompostCreate, MSWIncinerationCreate, \
    MSWLandfillCreate, MSWRecyclingCreate, \
    PlasticRecyclingCreate, PlasticIncinerationCreate, PlasticLandfillCreate, \
    PlasticReportedCreate, PlasticImportCreate, PlasticExportCreate, \
    PlasticReExportCreate, ScenarioCreate, ScenarioDetail, ScenarioList, \
    run_calculations, ScenarioResults, ScenarioReview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('disclaimers/', include('disclaimers.urls', namespace='disclaimers')),
    path('support/', include('support.urls', namespace='support')),
    path('teams/', include('teams.urls', namespace='teams')),

    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),

    path('scenario/', ScenarioList.as_view(), name='scenario'),
    path('scenario/create/', ScenarioCreate.as_view(), name='scenario_create'),
    path('scenario/<int:pk>/',
         ScenarioDetail.as_view(),
         name='scenario_detail'),

    path('scenario/<int:pk>/run/', run_calculations, name='run_calculations'),

    path('scenario/<int:pk>/review/',
         ScenarioReview.as_view(),
         name='scenario_review'),

    path('scenario/<int:pk>/results/',
         ScenarioResults.as_view(),
         name='scenario_results'),

    path('scenario/<int:pk>/conditions/',
         ConditionsDetail.as_view(),
         name='conditions_detail'),
    path('scenario/<int:pk>/conditions/create',
         ConditionsCreate.as_view(),
         name='conditions_create'),

    # path('scenario/<int:pk>/msw_composition/',
    #    MSWCompositionDetail.as_view(),
    #    name='msw_composition_detail'),
    path('scenario/<int:pk>/msw_composition/create',
         MSWCompositionCreate.as_view(),
         name='msw_composition_create'),

    # path('scenario/<int:pk>/msw_recycling/',
    #      MSWRecyclingDetail.as_view(),
    #      name='msw_recycling_detail'),
    path('scenario/<int:pk>/msw_recycling/create',
         MSWRecyclingCreate.as_view(),
         name='msw_recycling_create'),

    # path('scenario/<int:pk>/msw_incineration/',
    #      MSWIncinerationDetail.as_view(),
    #      name='msw_incineration_detail'),
    path('scenario/<int:pk>/msw_incineration/create',
         MSWIncinerationCreate.as_view(),
         name='msw_incineration_create'),

    # path('scenario/<int:pk>/msw_landfill/',
    #      MSWLandfillDetail.as_view(),
    #      name='msw_landfill_detail'),
    path('scenario/<int:pk>/msw_landfill/create',
         MSWLandfillCreate.as_view(),
         name='msw_landfill_create'),

    # path('scenario/<int:pk>/msw_compost/',
    #      MSWCompostDetail.as_view(),
    #      name='msw_compost_detail'),
    path('scenario/<int:pk>/msw_compost/create',
         MSWCompostCreate.as_view(),
         name='msw_compost_create'),

    # ################################################################

    path('scenario/<int:pk>/plastic_recycling_create/create',
         PlasticRecyclingCreate.as_view(),
         name='plastic_recycling_create'),

    path('scenario/<int:pk>/plastic_incineration_create/create',
         PlasticIncinerationCreate.as_view(),
         name='plastic_incineration_create'),

    path('scenario/<int:pk>/plastic_landfill_create/create',
         PlasticLandfillCreate.as_view(),
         name='plastic_landfill_create'),

    path('scenario/<int:pk>/plastic_reported_create/create',
         PlasticReportedCreate.as_view(),
         name='plastic_reported_create'),

    path('scenario/<int:pk>/plastic_imported_create/create',
         PlasticImportCreate.as_view(),
         name='plastic_imported_create'),

    path('scenario/<int:pk>/plastic_exported_create/create',
         PlasticExportCreate.as_view(),
         name='plastic_exported_create'),

    path('scenario/<int:pk>/plastic_reexported_create/create',
         PlasticReExportCreate.as_view(),
         name='plastic_reexported_create'),
]

src/teams/urls.py
# urls.py (teams)
# !/usr/bin/env python3
# coding=utf-8
# py-lint: disable=invalid-name
# We disable the invalid name because urlpatterns is the Django default

"""
URLs related to managing teams of users.

Available functions:
- REST api for teams
- Team management
"""

from django.urls import re_path
from teams.views import APITeamListView, APITeamDetailView, \
    APITeamMembershipListView, APITeamMembershipDetailView, \
    TeamCreateView, TeamManagementView, TeamEditView, TeamListView

app_name = 'teams'

urlpatterns = [

    # REST api for teams.
    re_path(r'^api/team/$', APITeamListView.as_view(), name='api_team_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/$', APITeamDetailView.as_view(),
            name='api_team_detail'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/$',
            APITeamMembershipListView.as_view(),
            name='api_team_membership_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/(?P<membership_id>\d+)/$',
            APITeamMembershipDetailView.as_view(),
            name='api_team_membership_detail'),

    # Team management.
    re_path(r'^team/$', TeamCreateView.as_view(), name='team_create'),
    re_path(r'^list/$', TeamListView.as_view(), name='team_list'),
    re_path(r'^team/(?P<team_id>\d+)/manage$', TeamManagementView.as_view(),
            name='team_manage'),
    re_path(r'^team/(?P<team_id>\d+)/edit$', TeamEditView.as_view(),
            name='team_edit'),
]

src/teams/forms.py
# forms.py (teams)
# !/usr/bin/env python3
# coding=utf-8
# py-lint: disable=R0903
"""
Forms for managing teams.

Available functions:
- Form For Creating or Updating a Project
"""

from django import forms
from django.utils.translation import gettext_lazy as _
from teams.models import Team


class TeamManagementForm(forms.ModelForm):
    """Form For Creating or Updating a Project."""

    # Name of the project
    name = forms.CharField(
        label=_("Name"),
        help_text="Project names must be unique",
        widget=forms.TextInput(attrs={'class': 'usa-input'}),
        required=True)

    class Meta:
        """Meta data for the Team Management Form."""

        model = Team
        fields = ("name", )

src/teams/views.py
# views.py (accounts)
# !/usr/bin/env python3
# coding=utf-8
# py-lint: disable=C0301,R0901,E1101,R0912
"""
Team management views.

Available functions:
- Create the form view
- View to edit a team name
- Team Management Form
"""

from datetime import datetime
from io import BytesIO
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView, status, Http404
from rest_framework import permissions
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.views.generic import FormView, ListView
from django.test.client import RequestFactory
from accounts.models import User
from teams.forms import TeamManagementForm, Team
from teams.models import TeamMembership
from teams.serializers import TeamSerializer, UserSerializer, \
    TeamMembershipSerializer, TeamMembershipModifySerializer


def is_user_member(user, team=None):
    """
    Check user membership.

    Check if the given user is a member of the given team or if the user is
    a member of any team when team=None.
    """
    if team:
        return TeamMembership.objects.filter(team_id=team.id,
                                             member_id=user.id).exists()
    return TeamMembership.objects.filter(member_id=user.id).exists()


def can_user_edit_team(user, team_id):
    """
    Check if a user can edit a team.

    Check team membership and user super status to
    decide if the given user can modify the given team.
    """
    membership = TeamMembership.objects.filter(team_id=team_id,
                                               member_id=user.id).first()
    return membership.can_edit or user.is_superuser


class TeamListView(LoginRequiredMixin, ListView):
    """
    New class to return a teams list view.

    This will serve as the management view where users can view their teams,
    edit their teams, and create new teams.
    """

    model = Team
    context_object_name = 'teams'
    template_name = 'team_list.html'

    def get_queryset(self):
        """
        Get a list of teams.

        Override the default queryset with the set of teams of
        which the requesting user is member.
        """
        user = self.request.user
        return Team.objects.filter(
            members=user).order_by('name').select_related(
                "created_by", "last_modified_by").prefetch_related(
                    "team_memberships", "team_memberships__member").all()


class TeamCreateView(FormView):
    """Class containing the view to create a new team."""

    form_class = TeamManagementForm
    template = 'team_create.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        """Display the project create form."""
        form = TeamManagementForm()
        return render(request, self.template, {'form': form})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Save the changes to the user form."""
        form = self.form_class(request.POST)
        if form.is_valid():
            team_instance = form.save(commit=False)
            # Team creator.
            team_instance.created_by = request.user
            # When and by whom the project was created.
            date_now = datetime.now()
            team_instance.created_date = date_now
            team_instance.created_by = request.user
            # When and by whom the project was last modified.
            team_instance.last_modified_date = date_now
            team_instance.last_modified_by = request.user
            # Save the project
            team_instance.save()

            # Add a membership for the requesting user.
            membership_instance = TeamMembership()
            membership_instance.added_date = date_now
            membership_instance.member = request.user
            membership_instance.team = team_instance
            membership_instance.is_owner = True
            membership_instance.can_edit = True
            membership_instance.save()

            return HttpResponseRedirect(
                reverse('team_manage', kwargs={'team_id': team_instance.id}))

        return render(request, self.template, locals())


class TeamEditView(FormView):
    """View to edit a team name."""

    template = 'team_edit.html'
    form_class = TeamManagementForm

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        """Display the project create form."""
        ctx = {}
        ctx['team_id'] = kwargs["team_id"] if kwargs is not None and \
            'team_id' in kwargs else None
        if ctx['team_id'] is not None:
            if can_user_edit_team(request.user, ctx['team_id']):
                ctx['team_data'] = APITeamDetailView.as_view()(
                    request, team_id=ctx['team_id'],
                    format='json').rendered_content
                ctx['team'] = JSONParser().parse(BytesIO(
                    ctx['team_data']))['name']
                return render(request, self.template, ctx)
        return HttpResponseRedirect('/teams/list/')

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Save the changes to the user form."""
        ctx = {}
        ctx['params'] = request.POST
        ctx['team_id'] = kwargs["team_id"] if kwargs is not None and \
            'team_id' in kwargs else None

        if ctx['team_id'] is not None:
            if not can_user_edit_team(request.user, ctx['team_id']):
                return HttpResponseRedirect('/teams/list/')

            # Update the team name.
            ctx['team_obj'] = Team.objects.get(id=ctx['team_id'])
            if ctx['team_obj'] is not None:
                ctx['name'] = ctx['params']['name'] if \
                    'name' in ctx['params'] else None
                ctx['name'] = ctx['name'].strip()
                if ctx['name'] is not None and ctx['name']:
                    ctx['team_obj'].name = ctx['name']
                    ctx['team_obj'].save()
                else:
                    ctx['error_msg'] = "Invalid team name."
            else:
                ctx['error_msg'] = "Invalid team id specified."

            # Retrieve the updated data and render the view.
            get_request = RequestFactory().get('/')
            get_request.user = request.user
            ctx['team_data'] = APITeamDetailView.as_view()(
                get_request, team_id=ctx['team_id'],
                format='json').rendered_content
            ctx['team'] = JSONParser().parse(BytesIO(ctx['team_data']))
            # return render(request, self.template, ctx)
            return HttpResponseRedirect('/teams/list/')

        # We should never get here, so just redirect to the home.
        return HttpResponseRedirect(reverse('home'))


class TeamManagementView(FormView):
    """Class containing methods to manage teams."""

    template = 'team_manage.html'
    form_class = TeamManagementForm

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        """Display the project create form."""
        ctx = {}
        ctx['team_id'] = kwargs["team_id"] if kwargs is not None and \
            'team_id' in kwargs else None
        if ctx['team_id'] is not None:
            ctx['team_data'] = APITeamDetailView.as_view()(
                request, team_id=ctx['team_id'],
                format='json').rendered_content
            ctx['team'] = JSONParser().parse(BytesIO(ctx['team_data']))
            ctx['nonmembers_data'] = APITeamMembershipListView.as_view()(
                request, team_id=ctx['team_id'], nonmember=1,
                format='json').rendered_content
            ctx['nonmembers'] = JSONParser().parse(
                BytesIO(ctx['nonmembers_data']))

            membership = TeamMembership.objects.filter(
                team_id=ctx['team_id'], member_id=request.user).first()
            ctx['user_can_edit'] = membership.can_edit

            return render(request, self.template, ctx)
        return HttpResponseRedirect('/teams/list/')

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Save the changes to the user form."""
        ctx = {}
        ctx['params'] = request.POST
        ctx['command'] = ctx['params']["command"] if \
            "command" in ctx['params'] else None
        ctx['team_id'] = kwargs["team_id"] if kwargs is not None and \
            'team_id' in kwargs else None
        if not can_user_edit_team(request.user, ctx['team_id']):
            return HttpResponseRedirect('/teams/list/')

        ctx['team_obj'] = Team.objects.filter(id=ctx['team_id']).first()
        if ctx['team_obj'] is not None and ctx['command'] is not None:
            # If the request.user cannot edit the current team, do nothing.
            membership = TeamMembership.objects.filter(
                team_id=ctx['team_id'], member_id=request.user).first()
            ctx['user_can_edit'] = membership.can_edit
            if not membership.can_edit:
                return HttpResponseRedirect('/teams/team/%s/manage' %
                                            ctx['team_id'])

            if ctx['command'] == 'adduser':
                # Add a user membership to the team.
                user_id = int(ctx['params']['user_id']) if \
                    'user_id' in ctx['params'] else None
                if user_id is not None:
                    # Check if the user already has a membership, this can
                    # happen if the user reloads the page.
                    ctx['membership_list'] = TeamMembership.objects.filter(
                        team_id=ctx['team_id'], member_id=user_id).all()

src/teams/templates/team_create.html
{% extends 'main/base.html' %}
{% load humanize %}

{% block content %}
<div class="white-box">
    <form method="post" action="{% url 'teams:team_create' %}">
        {% if form.errors %}
        <div class="usa-alert usa-alert--error" role="alert">
            <div class="usa-alert__body">
                <h5 class="usa-alert__heading">Please correct the following errors</h5>
                {% for field in form %}
                {% if field.errors %}
                <p class="usa-alert__text">{{field.label_tag}} {{ field.errors|striptags }}</p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}
        {% if success %}
        <div class="usa-alert usa-alert--success">
            <div class="usa-alert__body">
                <p class="usa-alert__text">Your team has been created.</p>
            </div>
        </div>
        {% endif %}

        {% csrf_token %}
        <h3>Create a Project Team</h3>
        <h4>Select a name for your team.</h4>
        <div class="usa-form-group">
            <label for="name" class="usa-label">{{form.name.label_tag}}</label>
            {{form.name}}
        </div>

        <div class="button-group">
            <button type="submit" class="usa-button">Save</button>
            <a type="reset" class="usa-button button--danger" href="{% url 'teams:team_list' %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

src/teams/templates/team_edit.html
{% extends 'main/base.html' %}
{% load humanize %}
{% block content %}
<h4>Edit the team name for '{{team}}'</h4>
<form class="form-horizontal" method="post" action="/teams/team/{{team.id}}/edit">
    {% csrf_token %}
    <div class="usa-form-group">
        <label for="name" class="usa-label">Name</label>
        <input class="usa-input" type="text" name="name" value="{{team.name}}"/>
    </div>
    <div class="button-group">
        <button type="submit" class="usa-button">Save</button>
        <a type="reset" class="usa-button button--danger" href="{% url 'teams:team_list' %}">Cancel</a>
    </div>
</form>
{% endblock %}

src/teams/templates/team_list.html
{% extends 'main/base.html' %} {% load static %} {% block content %}
<h2>Team Management</h2>
<hr />
<h4>{{user.username}}'s Teams</h4>
<table class="usa-table">
  <thead>
    <tr>
      <th data-sortable scope="col">Team Name</th>
      <th data-sortable scope="col">Team Created By</th>
      <th data-sortable scope="col">Team Last Modified</th>
    </tr>
  </thead>
  <tbody>
    {% if teams %}
    {% for team in teams %}
    <tr id="{{team.id}}" onclick="rowClick('{{team.id}}')">
      <th scope="row">{{team.name}}</th>
      <td>{{team.created_by}}</td>
      <td>{{team.last_modified_date|date:"Y-m-d"}}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr><td colspan="3">You aren't a member of any Teams!</td></tr>
    {% endif %}
  </tbody>
</table>
<div class="usa-sr-only usa-table__announcement-region" aria-live="polite"></div>

<div class="button-group">
  <button class="usa-button modSelectedButton" onclick="viewEditTeam(this, 'edit')" disabled>
    <svg class="usa-icon usa-icon--size-3">
      <use href="https://www.epa.gov/themes/epa_theme/images/sprite.svg#edit"></use>
    </svg>
    <span class="custom-icon-label">Edit Team</span>
  </button>
  <button class="usa-button modSelectedButton" onclick="viewEditTeam(this, 'manage')" disabled>
    <svg class="usa-icon usa-icon--size-3">
      <use href="https://www.epa.gov/themes/epa_theme/images/sprite.svg#accessibility_new"></use>
    </svg>
    <span class="custom-icon-label">View/Manage Members</span>
  </button>
  <a class="usa-button" href="{% url 'teams:team_create' %}">
    <svg class="usa-icon usa-icon--size-3">
      <use href="https://www.epa.gov/themes/epa_theme/images/sprite.svg#add"></use>
    </svg>
    <span class="custom-icon-label">Create a new Team</span>
  </a>
</div>
{% endblock %}

{% block extend_js %}
<!-- NOTE: JQuery is already included inside base.html... -->
<!-- NOTE: Not sure why, but JQuery won't work unless I include again here. -->
<script src="https://www.epa.gov/core/assets/vendor/jquery/jquery.min.js?v=3.6.0"></script>
<script src="{% static 'scripts/app.js' %}"></script>
{% endblock %} {% block scripts %}
<script>
  function viewEditTeam(btn, method) {
    if ($(btn).attr("disabled")) return;
    window.location.href = "/teams/team/" + $(btn).attr("id") + "/" + method;
  }
</script>
{% endblock %}

src/teams/templates/team_manage.html
{% extends 'main/base.html' %} {% load humanize %} {% block content %}

<h3>Manage memberships for team '{{team.name}}'</h3>

{% if team.team_memberships %}
<table class="usa-table usa-table--borderless">
  <caption>
    Total members: {{team.team_memberships | length}}
  </caption>
  <thead>
    <tr>
      <th scope="col">Member</th>
      <th scope="col">Date Added to Team</th>
      <th scope="col">Permissions</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
    {% for membership in team.team_memberships %}
    <tr>
      <th scope="row">
        {% if membership.member.first_name %}
        {{membership.member.first_name}} {{membership.member.last_name}}
        {% else %}
        {{membership.member.username}}
        {% endif %} <!-- endif membership.member.first_name -->
      </th>
      <td>{{membership.added_date|date:"Y-m-d"}}</td>
      <td>
        {% if membership.is_owner %} Owner {% else %} {% if user_can_edit %}
        <form method="post" action="{% url 'teams:team_manage' team_id %}">
          {% csrf_token %}
          <input type="hidden" name="command" value="canedit" />
          <input type="hidden" name="user_id" value="{{membership.member.id}}"/>
          <select type="submit" name="can_edit" onchange="this.form.submit()"
                  class="form-item__select">
            <option value="True" {% if membership.can_edit %} selected {% endif %}>
              Can edit
            </option>
            <option value="False" {% if not membership.can_edit %} selected {% endif %}>
              Can view
            </option>
          </select>
        </form>
        {% else %}
        {% if membership.can_edit %}
        Can edit
        {% else %}
        Can view
        {% endif %} <!-- endif membership.can_edit -->
        {% endif %} <!-- endif user_can_edit -->
        {% endif %} <!-- endif membership.is_owner -->
      </td>
      <td>
        {% if membership.is_owner == False and user_can_edit %}
        <form method="post" action="{% url 'teams:team_manage' team_id %}">
          {% csrf_token %}
          <input type="hidden" name="command" value="deleteuser" />
          <input type="hidden" name="user_id" value="{{membership.member.id}}"/>
          <button class="usa-button usa-button--unstyled" type="submit">
            <svg class="usa-icon usa-icon--size-3">
              <use href="https://www.epa.gov/themes/epa_theme/images/sprite.svg#delete"></use>
            </svg>
          </button>
        </form>
        {% endif %} <!-- endif membership.is_owner == False and user_can_edit -->
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if user_can_edit %}
<table class="usa-table usa-table--borderless">
  <caption>
    Add members: {{nonmembers | length}} available
  </caption>
  <thead>
    <tr>
      <th scope="col">User</th>
      <th scope="col">Email</th>
      <th scope="col">Add Member</th>
    </tr>
  </thead>
  <tbody>
    {% if nonmembers %}
    {% for nonmember in nonmembers %}
    <tr>
      <th scope="row">
        {% if nonmember.first_name %}
        {{nonmember.first_name}} {{nonmember.last_name}}
        {% else %}
        {{nonmember.username}}
        {% endif %} <!-- endif nonmember.first_name -->
      </th>
      <td>{{nonmember.email}}</td>
      <td>
        <form method="post" action="{% url 'teams:team_manage' team_id %}">
          {% csrf_token %}
          <input type="hidden" name="command" value="adduser" />
          <input type="hidden" name="user_id" value="{{nonmember.id}}" />
          <button class="usa-button usa-button--unstyled" type="submit">
            <svg class="usa-icon usa-icon--size-3">
              <use href="https://www.epa.gov/themes/epa_theme/images/sprite.svg#group_add"></use>
            </svg>
          </button>
        </form>
      </td>
    </tr>
    {% endfor %} <!-- endfor nonmember in nonmembers -->
    {% else %} <!-- else no available nonmembers -->
    <tr>
      <td colspan="3">No users available to add!</td>
    </tr>
    {% endif %} <!-- endif nonmembers -->
  </tbody>
</table>
{% endif %} <!-- endif user_can_edit -->

<a type="reset" class="usa-button button--danger" href="{% url 'teams:team_list' %}" >Back to Teams List</a>
{% endif %} <!-- endif team.team_memberships -->
{% endblock %}