src/plastics_eol/urls.py
# urls.py (plastics_eol)
# !/usr/bin/env python3
# coding=utf-8

from django.contrib import admin
from django.urls import path, include
from .views import home, contact, about, ConditionsCreate, ConditionsDetail, \
    MSWCompositionCreate, MSWCompostCreate, MSWIncinerationCreate, \
    MSWLandfillCreate, MSWRecyclingCreate, \
    PlasticRecyclingCreate, PlasticIncinerationCreate, PlasticLandfillCreate, \
    PlasticReportedCreate, PlasticImportCreate, PlasticExportCreate, \
    PlasticReExportCreate, ScenarioCreate, ScenarioDetail, ScenarioList, \
    run_calculations, ScenarioResults, ScenarioReview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('disclaimers/', include('disclaimers.urls', namespace='disclaimers')),
    path('support/', include('support.urls', namespace='support')),
    path('teams/', include('teams.urls', namespace='teams')),

    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),

    path('scenario/', ScenarioList.as_view(), name='scenario'),
    path('scenario/create/', ScenarioCreate.as_view(), name='scenario_create'),
    path('scenario/<int:pk>/',
         ScenarioDetail.as_view(),
         name='scenario_detail'),

    path('scenario/<int:pk>/run/', run_calculations, name='run_calculations'),

    path('scenario/<int:pk>/review/',
         ScenarioReview.as_view(),
         name='scenario_review'),

    path('scenario/<int:pk>/results/',
         ScenarioResults.as_view(),
         name='scenario_results'),

    path('scenario/<int:pk>/conditions/',
         ConditionsDetail.as_view(),
         name='conditions_detail'),
    path('scenario/<int:pk>/conditions/create',
         ConditionsCreate.as_view(),
         name='conditions_create'),

    # path('scenario/<int:pk>/msw_composition/',
    #    MSWCompositionDetail.as_view(),
    #    name='msw_composition_detail'),
    path('scenario/<int:pk>/msw_composition/create',
         MSWCompositionCreate.as_view(),
         name='msw_composition_create'),

    # path('scenario/<int:pk>/msw_recycling/',
    #      MSWRecyclingDetail.as_view(),
    #      name='msw_recycling_detail'),
    path('scenario/<int:pk>/msw_recycling/create',
         MSWRecyclingCreate.as_view(),
         name='msw_recycling_create'),

    # path('scenario/<int:pk>/msw_incineration/',
    #      MSWIncinerationDetail.as_view(),
    #      name='msw_incineration_detail'),
    path('scenario/<int:pk>/msw_incineration/create',
         MSWIncinerationCreate.as_view(),
         name='msw_incineration_create'),

    # path('scenario/<int:pk>/msw_landfill/',
    #      MSWLandfillDetail.as_view(),
    #      name='msw_landfill_detail'),
    path('scenario/<int:pk>/msw_landfill/create',
         MSWLandfillCreate.as_view(),
         name='msw_landfill_create'),

    # path('scenario/<int:pk>/msw_compost/',
    #      MSWCompostDetail.as_view(),
    #      name='msw_compost_detail'),
    path('scenario/<int:pk>/msw_compost/create',
         MSWCompostCreate.as_view(),
         name='msw_compost_create'),

    # ################################################################

    path('scenario/<int:pk>/plastic_recycling_create/create',
         PlasticRecyclingCreate.as_view(),
         name='plastic_recycling_create'),

    path('scenario/<int:pk>/plastic_incineration_create/create',
         PlasticIncinerationCreate.as_view(),
         name='plastic_incineration_create'),

    path('scenario/<int:pk>/plastic_landfill_create/create',
         PlasticLandfillCreate.as_view(),
         name='plastic_landfill_create'),

    path('scenario/<int:pk>/plastic_reported_create/create',
         PlasticReportedCreate.as_view(),
         name='plastic_reported_create'),

    path('scenario/<int:pk>/plastic_imported_create/create',
         PlasticImportCreate.as_view(),
         name='plastic_imported_create'),

    path('scenario/<int:pk>/plastic_exported_create/create',
         PlasticExportCreate.as_view(),
         name='plastic_exported_create'),

    path('scenario/<int:pk>/plastic_reexported_create/create',
         PlasticReExportCreate.as_view(),
         name='plastic_reexported_create'),
]

src/support/urls.py
# urls.py (support)
# !/usr/bin/env python3
# coding=utf-8
# pylint: skip-file
# We disable the invalid name because urlpatterns is the Django default

"""URLs and routing for the Support module."""

from django.urls import re_path
from .views import index, UserManualView, download_manual, EventsView, \
    ReferencesView, event_file_download, SuggestionCreateView, \
    SuggestionEditView, delete_support, list_supports, show_support, \
    file_upload_support, delete_support_attachment, create_support_type, \
    edit_support_type, delete_support_type, list_support_types, \
    show_support_type, create_priority, edit_priority, delete_priority, \
    list_priorities, show_priority

app_name = 'support'

urlpatterns = [
    re_path(r'^$', index),
    re_path(r'^index/$', index, name='go_to_support'),

    re_path(
        r'^documentation/$', UserManualView.as_view(), name="documentation"),
    re_path(r'^download_manual/$', download_manual, name="download_manual"),
    re_path(r'events/', EventsView.as_view(), name='events'),
    re_path(r'references/', ReferencesView.as_view(), name='references'),

    re_path(
        r'^files/(?P<file_name>.+)/$', event_file_download,
        name='event_file_download'),

    re_path(r'^create/(?P<support_type_name>\w+)/$',
            SuggestionCreateView.as_view(), name='create_support'),
    re_path(r'^edit/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$',
            SuggestionEditView.as_view(), name='edit_support'),
    re_path(r'^delete/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$',
            delete_support, name='delete_support'),
    re_path(r'^list/(?P<support_type_name>\w+)/$',
            list_supports, name='list_supports'),
    re_path(r'^show/(?P<obj_id>\d+)/$', show_support, name='show_support'),

    # new
    re_path(r'^file/upload/(?P<obj_id>\d+)/$',
            file_upload_support, name='file_upload_support'),
    re_path(r'^support_attachment/delete/(?P<obj_id>\d+)/$',
            delete_support_attachment, name='delete_support_attachment'),

    re_path(r'^type/create/$',
            create_support_type, name='create_support_type'),
    re_path(r'^type/edit/(?P<obj_id>\d+)/$',
            edit_support_type, name='edit_support_type'),
    re_path(r'^type/delete/(?P<obj_id>\d+)/$',
            delete_support_type, name='delete_support_type'),
    re_path(r'^type/list/$', list_support_types, name='list_support_types'),
    re_path(r'^type/show/(?P<obj_id>\d+)/$',
            show_support_type, name='show_support_type'),

    re_path(r'^priority/create/$',
            create_priority, name='create_priority'),
    re_path(r'^priority/edit/(?P<obj_id>\d+)/$',
            edit_priority, name='edit_priority'),
    re_path(r'^priority/delete/(?P<obj_id>\d+)/$',
            delete_priority, name='delete_priority'),
    re_path(r'^priority/list/$',
            list_priorities, name='list_priorities'),
    re_path(r'^priority/show/(?P<obj_id>\d+)/$',
            show_priority, name='show_priority'),
]

src/teams/urls.py
# urls.py (teams)
# !/usr/bin/env python3
# coding=utf-8
# py-lint: disable=invalid-name
# We disable the invalid name because urlpatterns is the Django default

"""
URLs related to managing teams of users.

Available functions:
- REST api for teams
- Team management
"""

from django.urls import re_path
from teams.views import APITeamListView, APITeamDetailView, \
    APITeamMembershipListView, APITeamMembershipDetailView, \
    TeamCreateView, TeamManagementView, TeamEditView, TeamListView

app_name = 'teams'

urlpatterns = [

    # REST api for teams.
    re_path(r'^api/team/$', APITeamListView.as_view(), name='api_team_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/$', APITeamDetailView.as_view(),
            name='api_team_detail'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/$',
            APITeamMembershipListView.as_view(),
            name='api_team_membership_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/(?P<membership_id>\d+)/$',
            APITeamMembershipDetailView.as_view(),
            name='api_team_membership_detail'),

    # Team management.
    re_path(r'^team/$', TeamCreateView.as_view(), name='team_create'),
    re_path(r'^list/$', TeamListView.as_view(), name='team_list'),
    re_path(r'^team/(?P<team_id>\d+)/manage$', TeamManagementView.as_view(),
            name='team_manage'),
    re_path(r'^team/(?P<team_id>\d+)/edit$', TeamEditView.as_view(),
            name='team_edit'),
]

src/support/forms.py
# py (support)
# !/usr/bin/env python3
# coding=utf-8
# pylint: skip-file
"""
Form used to manage support issues.

Available functions:
"""

from django.forms import ModelForm, CharField, TextInput, Textarea, DateField
from django.utils.translation import gettext_lazy as _
from support.models import Support, Priority, SupportType


class SupportForm(ModelForm):
    """A Form For Creating a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Support form to send to Django Admin."""
        super(SupportForm, self).__init__(*args, **kwargs)

    required_css_class = 'required'

    id = CharField(label=_("Reference Num"),
                   widget=TextInput(attrs={
                       'class': 'usa-input',
                       'readonly': 'readonly'
                   }),
                   required=False)
    subject = CharField(label=_("Subject"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)

    the_description = CharField(label=_("Description"),
                                widget=Textarea(attrs={'class': 'usa-input'}),
                                required=True)
    weblink = CharField(label=_("Email Address"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)

    class Meta:
        """Support link."""

        model = Support
        fields = (
            "id",
            "subject",
            "the_description",
            "weblink",
        )


class SupportAdminForm(ModelForm):
    """A Form For Responding To a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Support Django Admin form."""
        super(SupportAdminForm, self).__init__(*args, **kwargs)

    required_css_class = 'required'

    id = CharField(label=_("Reference Num"),
                   widget=TextInput(attrs={
                       'class': 'usa-input',
                       'readonly': 'readonly'
                   }),
                   required=False)
    subject = CharField(label=_("Subject"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)
    date_resolved = DateField(
        label=_("Date Resolved"),
        widget=TextInput(attrs={'class': 'usa-input date-control'}),
        required=False)
    the_description = CharField(label=_("Description"),
                                widget=Textarea(attrs={'class': 'usa-input'}),
                                required=True)
    weblink = CharField(label=_("Email Address"),
                        widget=TextInput(attrs={'class': 'usa-input'}),
                        required=True)
    review_notes = CharField(label=_("Review Notes"),
                             widget=Textarea(attrs={'class': 'usa-input'}),
                             help_text="Notes from review of suggestion",
                             required=False)

    class Meta:
        """All fields to complete support form."""

        model = Support
        fields = (
            "id",
            "subject",
            "the_description",
            "weblink",
            "date_resolved",
            "review_notes",
        )


class SupportTypeForm(ModelForm):
    """A Form For Creating a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Form type."""
        super(SupportTypeForm, self).__init__(*args, **kwargs)

    required_css_class = 'required'
    the_name = CharField(label=_("Support Type"),
                         widget=TextInput(attrs={'class': 'usa-input'}),
                         required=False)

    class Meta:
        """Name form."""

        model = SupportType
        fields = ("the_name", )


class PriorityForm(ModelForm):
    """A Form For Creating a Support Issue."""

    def __init__(self, *args, **kwargs):
        """Form priority."""
        super(PriorityForm, self).__init__(*args, **kwargs)

    the_name = CharField(label=_("Priority"),
                         widget=TextInput(attrs={'class': 'usa-input'}),
                         required=False)

    class Meta:
        """Form priority.."""

        model = Priority
        fields = ("the_name", )

src/support/templates/edit/admin/edit_support_admin.html
{% extends 'base/site_base_support.html' %}
{% block support_content %}
<script>
    $(function () {
        var ul = $('#upload ul');
        // Change this to the location of your server-side upload handler:
        var url = '/support/file/upload/{{obj.id}}/';

        $('#drop a').click(function(){
            // Simulate a click on the file input button
            // to show the file browser dialog
            $(this).parent().find('input').click();
        });

        // Initialize the jQuery File Upload plugin
        $('#upload').fileupload({
            // This element will accept file drag/drop uploading
            dropZone: $('#drop'),

            // This function is called when a file is added to the queue;
            // either via the browse button, or via drag/drop:
            add: function (e, data) {
                var tpl = $('<li class="working"><input type="text" value="0" data-width="48" data-height="48"'+
                ' data-fgColor="#0788a5" data-readOnly="1" data-bgColor="#3e4043" /><p></p><span></span></li>');
                // Append the file name and file size
                tpl.find('p').text(data.files[0].name).append('<i>' + formatFileSize(data.files[0].size) + '</i>');
                // Add the HTML to the UL element
                data.context = tpl.appendTo(ul);
                // Initialize the knob plugin
                tpl.find('input').knob();
                // Listen for clicks on the cancel icon
                tpl.find('span').click(function(){
                if(tpl.hasClass('working')){
                    jqXHR.abort();
                }
                tpl.fadeOut(function(){
                    tpl.remove();
                });
            });

            // Automatically upload the file once it is added to the queue
            var jqXHR = data.submit();
        },

      progress: function(e, data){
            // Calculate the completion percentage of the upload
            var progress = parseInt(data.loaded / data.total * 100, 10);
            // Update the hidden input field and trigger a change
            // so that the jQuery knob plugin knows to update the dial
            data.context.find('input').val(progress).change();
            if(progress == 100){
                data.context.removeClass('working');
            }
        },

        fail:function(e, data){
            // Something has gone wrong!
            data.context.addClass('error');
        }
    });

    // Prevent the default action when a file is dropped on the window
    $(document).on('drop dragover', function (e) {
        e.preventDefault();
    });

    // Helper function that formats the file sizes
    function formatFileSize(bytes) {
        if (typeof bytes !== 'number') {
            return '';
        }
        if (bytes >= 1000000000) {
            return (bytes / 1000000000).toFixed(2) + ' GB';
        }
        if (bytes >= 1000000) {
            return (bytes / 1000000).toFixed(2) + ' MB';
        }
        return (bytes / 1000).toFixed(2) + ' KB';
    }
});
</script>

<h3>Edit Suggestion (Admin):</h3>
<form class="form-horizontal" enctype="multipart/form-data" method="post" action="." role="form" novalidate>
    {% csrf_token %}
    {% if form.errors %}
    <div class="usa-alert usa-alert--error" role="alert">
        <div class="usa-alert__body">
            <h5 class="usa-alert__heading">Please correct the following errors</h5>
            {% for field in form %}
            {% if field.errors %}
            <p class="usa-alert__text">{{field.label_tag}} {{ field.errors|striptags }}</p>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% if success %}
    <div class="usa-alert usa-alert--success">
        <div class="usa-alert__body">
            <p class="usa-alert__text">The progam has been created.</p>
        </div>
    </div>
    {% endif %}

    {% for field in form %}
    <div class="usa-form-group">
        <label class="usa-label">
            <div>{{field.label_tag}}</div>
            <div class="help-block">{{field.help_text}}</div>
        </label>
        {{field}}
        {% if field.errors %}
        <div class="usa-alert usa-alert--error" role="alert">
            <div class="usa-alert__body">
                <p class="usa-alert__text">{{field.errors.as_text}}</p>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}

    <div class="usa-form-group">
        <input type="submit" value="Submit" class="usa-button">
    </div>
</form>


{% if support_attachments %}
<table class="usa-table" id="support_attachments_table">
    <caption>File Attachments</caption>
    <thead id="support_attachments_head">
        <tr>
            <th data-sortable scope="col">Filename</th>
            <th data-sortable scope="col">Delete</th>
        </tr>
    </thead>
    <tbody id="support_attachments_body">
        {% for obj in support_attachments %}
            <tr>
                <th scope="row">
                    <a href="{{MEDIA_URL}}{{obj.attachment|urlencode}}">{{obj.the_name}}</a>
                </th>
                <td>
                    <a href="{% url 'support:delete_support_attachment' obj.id %}">Remove</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="usa-sr-only usa-table__announcement-region" aria-live="polite"></div>
{% endif %}

{% if support.id %}
<form id="upload" method="post" action="{% url 'support:file_upload_support' support.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    Drop Files ONLY Here
    <a>Browse</a>
    <input type="file" name="upl" multiple />
    <ul><!-- The file uploads will be shown here --></ul>
</form>
{% endif %}
{% endblock %}