src/accounts/urls.py
# urls.py (accounts)
# !/usr/bin/env python3
# coding=utf-8
# py-lint: disable=invalid-name
# We disable the invalid name because urlpatterns is the Django default.
# py-lint: disable=C0301

"""
Module related to urls for user accounts.

Available functions:
- Login
- View/edit profile
- New user registration
- Password Management
- Username management
"""

from django.urls import re_path
from accounts.views import login, logout, ProfileView, UserRegistrationView, \
    UserApprovalView, UserDenialView, PasswordResetRequestView, \
    PasswordResetConfirmView, UsernameReminderRequestView

app_name = 'accounts'

urlpatterns = [
    # Login.
    re_path(r'^login/$', login, name='login'),
    re_path(r'^logout/$', logout, name='logout'),

    # View/edit existing profile.
    re_path(r'^profile/$', ProfileView.as_view(), name='profile'),

    # New user registration.
    re_path(r'^register/$', UserRegistrationView.as_view(), name='register'),
    # Give admins a chance to approve or deny new users.
    re_path(r'^register/approve/(?P<uidb64>[0-9A-Za-z]+)/$',
        UserApprovalView.as_view(), name='register_approve'),
    re_path(r'^register/deny/(?P<uidb64>[0-9A-Za-z]+)/$',
        UserDenialView.as_view(), name='register_deny'),

    # Password management.
    re_path(r'^password/reset/$', PasswordResetRequestView.as_view(),
        name="password_reset"),

    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    re_path(r'^password/reset/confirm/$', PasswordResetConfirmView.as_view(),
        name='reset_password_confirm_no_token'),

    # Username management.
    re_path(r'^username/$', UsernameReminderRequestView.as_view(),
        name="username_reminder"),

]

src/plastics_eol/urls.py
# urls.py (plastics_eol)
# !/usr/bin/env python3
# coding=utf-8

from django.contrib import admin
from django.urls import path, include
from .views import home, contact, about, ConditionsCreate, ConditionsDetail, \
    MSWCompositionCreate, MSWCompostCreate, MSWIncinerationCreate, \
    MSWLandfillCreate, MSWRecyclingCreate, \
    PlasticRecyclingCreate, PlasticIncinerationCreate, PlasticLandfillCreate, \
    PlasticReportedCreate, PlasticImportCreate, PlasticExportCreate, \
    PlasticReExportCreate, ScenarioCreate, ScenarioDetail, ScenarioList, \
    run_calculations, ScenarioResults, ScenarioReview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('disclaimers/', include('disclaimers.urls', namespace='disclaimers')),
    path('support/', include('support.urls', namespace='support')),
    path('teams/', include('teams.urls', namespace='teams')),

    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),

    path('scenario/', ScenarioList.as_view(), name='scenario'),
    path('scenario/create/', ScenarioCreate.as_view(), name='scenario_create'),
    path('scenario/<int:pk>/',
         ScenarioDetail.as_view(),
         name='scenario_detail'),

    path('scenario/<int:pk>/run/', run_calculations, name='run_calculations'),

    path('scenario/<int:pk>/review/',
         ScenarioReview.as_view(),
         name='scenario_review'),

    path('scenario/<int:pk>/results/',
         ScenarioResults.as_view(),
         name='scenario_results'),

    path('scenario/<int:pk>/conditions/',
         ConditionsDetail.as_view(),
         name='conditions_detail'),
    path('scenario/<int:pk>/conditions/create',
         ConditionsCreate.as_view(),
         name='conditions_create'),

    # path('scenario/<int:pk>/msw_composition/',
    #    MSWCompositionDetail.as_view(),
    #    name='msw_composition_detail'),
    path('scenario/<int:pk>/msw_composition/create',
         MSWCompositionCreate.as_view(),
         name='msw_composition_create'),

    # path('scenario/<int:pk>/msw_recycling/',
    #      MSWRecyclingDetail.as_view(),
    #      name='msw_recycling_detail'),
    path('scenario/<int:pk>/msw_recycling/create',
         MSWRecyclingCreate.as_view(),
         name='msw_recycling_create'),

    # path('scenario/<int:pk>/msw_incineration/',
    #      MSWIncinerationDetail.as_view(),
    #      name='msw_incineration_detail'),
    path('scenario/<int:pk>/msw_incineration/create',
         MSWIncinerationCreate.as_view(),
         name='msw_incineration_create'),

    # path('scenario/<int:pk>/msw_landfill/',
    #      MSWLandfillDetail.as_view(),
    #      name='msw_landfill_detail'),
    path('scenario/<int:pk>/msw_landfill/create',
         MSWLandfillCreate.as_view(),
         name='msw_landfill_create'),

    # path('scenario/<int:pk>/msw_compost/',
    #      MSWCompostDetail.as_view(),
    #      name='msw_compost_detail'),
    path('scenario/<int:pk>/msw_compost/create',
         MSWCompostCreate.as_view(),
         name='msw_compost_create'),

    # ################################################################

    path('scenario/<int:pk>/plastic_recycling_create/create',
         PlasticRecyclingCreate.as_view(),
         name='plastic_recycling_create'),

    path('scenario/<int:pk>/plastic_incineration_create/create',
         PlasticIncinerationCreate.as_view(),
         name='plastic_incineration_create'),

    path('scenario/<int:pk>/plastic_landfill_create/create',
         PlasticLandfillCreate.as_view(),
         name='plastic_landfill_create'),

    path('scenario/<int:pk>/plastic_reported_create/create',
         PlasticReportedCreate.as_view(),
         name='plastic_reported_create'),

    path('scenario/<int:pk>/plastic_imported_create/create',
         PlasticImportCreate.as_view(),
         name='plastic_imported_create'),

    path('scenario/<int:pk>/plastic_exported_create/create',
         PlasticExportCreate.as_view(),
         name='plastic_exported_create'),

    path('scenario/<int:pk>/plastic_reexported_create/create',
         PlasticReExportCreate.as_view(),
         name='plastic_reexported_create'),
]

src/support/urls.py
# urls.py (support)
# !/usr/bin/env python3
# coding=utf-8
# pylint: skip-file
# We disable the invalid name because urlpatterns is the Django default

"""URLs and routing for the Support module."""

from django.urls import re_path
from .views import index, UserManualView, download_manual, EventsView, \
    ReferencesView, event_file_download, SuggestionCreateView, \
    SuggestionEditView, delete_support, list_supports, show_support, \
    file_upload_support, delete_support_attachment, create_support_type, \
    edit_support_type, delete_support_type, list_support_types, \
    show_support_type, create_priority, edit_priority, delete_priority, \
    list_priorities, show_priority

app_name = 'support'

urlpatterns = [
    re_path(r'^$', index),
    re_path(r'^index/$', index, name='go_to_support'),

    re_path(
        r'^documentation/$', UserManualView.as_view(), name="documentation"),
    re_path(r'^download_manual/$', download_manual, name="download_manual"),
    re_path(r'events/', EventsView.as_view(), name='events'),
    re_path(r'references/', ReferencesView.as_view(), name='references'),

    re_path(
        r'^files/(?P<file_name>.+)/$', event_file_download,
        name='event_file_download'),

    re_path(r'^create/(?P<support_type_name>\w+)/$',
            SuggestionCreateView.as_view(), name='create_support'),
    re_path(r'^edit/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$',
            SuggestionEditView.as_view(), name='edit_support'),
    re_path(r'^delete/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$',
            delete_support, name='delete_support'),
    re_path(r'^list/(?P<support_type_name>\w+)/$',
            list_supports, name='list_supports'),
    re_path(r'^show/(?P<obj_id>\d+)/$', show_support, name='show_support'),

    # new
    re_path(r'^file/upload/(?P<obj_id>\d+)/$',
            file_upload_support, name='file_upload_support'),
    re_path(r'^support_attachment/delete/(?P<obj_id>\d+)/$',
            delete_support_attachment, name='delete_support_attachment'),

    re_path(r'^type/create/$',
            create_support_type, name='create_support_type'),
    re_path(r'^type/edit/(?P<obj_id>\d+)/$',
            edit_support_type, name='edit_support_type'),
    re_path(r'^type/delete/(?P<obj_id>\d+)/$',
            delete_support_type, name='delete_support_type'),
    re_path(r'^type/list/$', list_support_types, name='list_support_types'),
    re_path(r'^type/show/(?P<obj_id>\d+)/$',
            show_support_type, name='show_support_type'),

    re_path(r'^priority/create/$',
            create_priority, name='create_priority'),
    re_path(r'^priority/edit/(?P<obj_id>\d+)/$',
            edit_priority, name='edit_priority'),
    re_path(r'^priority/delete/(?P<obj_id>\d+)/$',
            delete_priority, name='delete_priority'),
    re_path(r'^priority/list/$',
            list_priorities, name='list_priorities'),
    re_path(r'^priority/show/(?P<obj_id>\d+)/$',
            show_priority, name='show_priority'),
]

src/teams/urls.py
# urls.py (teams)
# !/usr/bin/env python3
# coding=utf-8
# py-lint: disable=invalid-name
# We disable the invalid name because urlpatterns is the Django default

"""
URLs related to managing teams of users.

Available functions:
- REST api for teams
- Team management
"""

from django.urls import re_path
from teams.views import APITeamListView, APITeamDetailView, \
    APITeamMembershipListView, APITeamMembershipDetailView, \
    TeamCreateView, TeamManagementView, TeamEditView, TeamListView

app_name = 'teams'

urlpatterns = [

    # REST api for teams.
    re_path(r'^api/team/$', APITeamListView.as_view(), name='api_team_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/$', APITeamDetailView.as_view(),
            name='api_team_detail'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/$',
            APITeamMembershipListView.as_view(),
            name='api_team_membership_list'),
    re_path(r'^api/team/(?P<team_id>\d+)/membership/(?P<membership_id>\d+)/$',
            APITeamMembershipDetailView.as_view(),
            name='api_team_membership_detail'),

    # Team management.
    re_path(r'^team/$', TeamCreateView.as_view(), name='team_create'),
    re_path(r'^list/$', TeamListView.as_view(), name='team_list'),
    re_path(r'^team/(?P<team_id>\d+)/manage$', TeamManagementView.as_view(),
            name='team_manage'),
    re_path(r'^team/(?P<team_id>\d+)/edit$', TeamEditView.as_view(),
            name='team_edit'),
]

src/plastics_eol/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}

<h1 class="page-title">TODO Title.</h1>
<p>TODO summary.</p>

{% endblock %}

src/plastics_eol/templates/main/app_scripts.html
<!-- Put app-specific scripts in this file. -->

src/plastics_eol/templates/main/base.html
<!DOCTYPE html>
<html class="no-js pattern-lab-content" lang="en" dir="ltr">
    {% include 'main/base_head.html' %}

    <main id="main" class="main" role="main" tabindex="-1">
      {% block main %}
      <div class="l-page">
        <div class="l-constrain">
          {% block content %} {% endblock %}
        </div>
      </div>
      {% endblock %}
    </main>

    {% include 'epa/footer.html' %}

    <a href="#" class="back-to-top" title="">
      <svg class="back-to-top__icon" role="img" aria-label="">
        <use href="https://www.epa.gov/themes/epa_theme/images/sprite.artifact.svg#arrow"></use>
      </svg>
    </a>
    {% include 'epa/scripts.html' %}
    {% include 'main/app_scripts.html' %}
    <!-- Custom Addition: Include any extra JS files: -->
    {% block extend_js %} {% endblock %}
    <!-- Custom Addition: Block where child pages will put script blocks: -->
    {% block scripts %}{% endblock %}
</html>

src/plastics_eol/templates/main/base_head.html
{% include 'epa/head.html' %}
{% load static %}
<!--
  Add any additional head content here. The content in this file should be
  specific to this app and will override any conflicting content from the EPA
  template. For example custom CSS.
-->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

{% include 'epa/section_banner.html' %}
{% include 'epa/header.html' %}

src/plastics_eol/templates/main/contact.html
{% extends 'main/base.html' %}

{% block content %}
<h2>Define USEPA Branch.</h2>
<h3><a href="#">Define Division with link to website.</a></h3>

<address>
  Define contact info for Devision.
</address>

<h3>US EPA Contacts</h3>
<address>
  <strong>Website Support:</strong> <a href="mailto:specht.jacob@epa.gov">Developer</a>
</address>

<h3>RMEERS Contractor Support Contacts</h3>
<address>
  <strong>Contractor Developer:</strong> <a href="mailto:specht.jacob@epa.gov;">Developer</a>
</address>

{% endblock %}

src/plastics_eol/templates/main/plastics_eol_navbar.html
<li class="menu__item">
  <a href="{% url 'home' %}" class="menu__link">Home</a>
</li>
<li class="menu__item">
  <a href="{% url 'about' %}" class="menu__link">About</a>
</li>
<li class="menu__item">
  <a href="{% url 'contact' %}" class="menu__link">Contact</a>
</li>

{% if user.is_authenticated %}
<li class="menu__item">
  <a href="{% url 'scenario' %}" class="menu__link">Scenario</a>
</li>

<li class="menu__item has-subnav">
  <button class="menu__link has-subnav usa-nav__link" aria-expanded="false">Teams</button>
  <ul class="menu menu__subnav is-wide">
    <li class="menu__item"><a href="/teams/list/" class="menu__link">Manage existing teams</a></li>
    <li class="menu__item"><a href="/teams/team/" class="menu__link">Create a new team</a></li>
  </ul>
</li>

<li class="menu__item has-subnav">
  <button class="menu__link has-subnav usa-nav__link" aria-expanded="false">
    Help/Suggestions
  </button>
  <ul class="menu menu__subnav is-wide">
    <li class="menu__item"><a href="{% url 'support:go_to_support' %}" class="menu__link">Suggestions</a></li>
    <li class="menu__item"><a href="{% url 'support:events' %}" class="menu__link">Upcoming Events</a></li>
    <li class="menu__item"><a href="{% url 'support:references' %}" class="menu__link">Project References</a></li>
  </ul>
</li>

<li class="menu__item has-subnav">
  <button class="menu__link has-subnav usa-nav__link" aria-expanded="false">
    Welcome
    {% if user.first_name %}
    {{user.first_name}}
    {% else %}
    {{user.username}}
    {% endif %}
  </button>
  <ul class="menu menu__subnav is-wide">
    <li class="menu__item"><a href="{% url 'accounts:profile' %}" class="menu__link">My profile</a></li>
    {% if user.is_staff %}
    <li class="menu__item"><a href="{% url 'admin:index' %}" class="menu__link">Admin Portal</a></li>
    {% endif %}
    <li class="menu__item"><a href="{% url 'accounts:logout' %}" class="menu__link">Logout</a></li>
  </ul>
</li>

{% else %}
<li class="menu__item">
  <a href="{% url 'accounts:register' %}" class="menu__link">Register</a>
</li>
<li class="menu__item">
  <a href="{% url 'accounts:login' %}" class="menu__link">Log-in</a>
</li>
{% endif %}